/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scala_exp_player_Nginx */

#ifndef _Included_com_scala_exp_player_Nginx
#define _Included_com_scala_exp_player_Nginx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scala_exp_player_Nginx
 * Method:    getPrefixPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scala_exp_player_Nginx_getPrefixPath
  (JNIEnv *, jobject);

/*
 * Class:     com_scala_exp_player_Nginx
 * Method:    setPrefixPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scala_exp_player_Nginx_setPrefixPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scala_exp_player_Nginx
 * Method:    setConfigPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scala_exp_player_Nginx_setConfigPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scala_exp_player_Nginx
 * Method:    startNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scala_exp_player_Nginx_startNative
  (JNIEnv *, jobject);

/*
 * Class:     com_scala_exp_player_Nginx
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scala_exp_player_Nginx_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     com_scala_exp_player_Nginx
 * Method:    setPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_scala_exp_player_Nginx_setPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scala_exp_player_Nginx
 * Method:    setHostName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_scala_exp_player_Nginx_setHostName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
