/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scala_exp_player_Nginx_NginxExecutor */

#ifndef _Included_com_scala_exp_player_Nginx_NginxExecutor
#define _Included_com_scala_exp_player_Nginx_NginxExecutor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scala_exp_player_Nginx_NginxExecutor_WAIT_TERM
#define com_scala_exp_player_Nginx_NginxExecutor_WAIT_TERM 50L
#ifdef __cplusplus
}
#endif
#endif
